/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.mobilitydata.gtfsvalidator.runner.ApplicationType;
import org.mobilitydata.gtfsvalidator.runner.ValidationRunner;
import org.mobilitydata.gtfsvalidator.runner.ValidationRunnerConfig;
import org.mobilitydata.gtfsvalidator.util.VersionResolver;

import java.io.File;
import java.nio.file.Path;


public class GtfsValidatorExample {

    public static void main(String[] args) throws Exception {

        ValidationRunnerConfig.Builder builder = ValidationRunnerConfig.builder();

        // Specify the source gtfs file
        builder.setGtfsSource(new File("testGtfsDataset.zip").toURI());
        // Specify the output directory
        builder.setOutputDirectory(Path.of("./output"));

        ValidationRunnerConfig validatorConfig = builder.build();

        // Run MobilityData validator.
        ValidationRunner runner = new ValidationRunner(new VersionResolver(ApplicationType.CLI));
        runner.run(validatorConfig);
        System.exit(0);
    }
}
